### ISSUE TITLE
Error: moduleId should be a string

### ISSUE THREAD

**Issue by Kraku** [lunzhang/ng2-grid#1]
Versions
-
Angular: 2.4.4
Webpack: 2.2.2
ng2-grid-component: 0.2.74

Console output
-
```
metadata_resolver.js:1085

Uncaught Error: moduleId should be a string in "NgGrid". See https://goo.gl/wIDDiL for more information.

If you're using Webpack you should inline the template and the styles, see https://goo.gl/X2J8zc.
```

Similar issues
-
https://github.com/jkuri/ng2-datepicker/issues/69
https://github.com/angular/angular-cli/issues/3576

**Comment by lunzhang** [comment]
I have updated the npm package with inline styles.  I will update build tasks later to change external css to inline.
